// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rss_Reader_BackEnd.Context;

#nullable disable

namespace Rss_Reader_BackEnd.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230307200936_UpdatingCategoryModels")]
    partial class UpdatingCategoryModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RssReader")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rss_Reader_BackEnd.Models.CategoryItem", b =>
                {
                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItemForeignKey")
                        .HasColumnType("int");

                    b.HasKey("CategoryName")
                        .HasName("Name");

                    b.HasIndex("ItemForeignKey");

                    b.ToTable("CategoryItem", "RssReader");
                });

            modelBuilder.Entity("Rss_Reader_BackEnd.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_ItemId");

                    b.ToTable("Item", "RssReader");
                });

            modelBuilder.Entity("Rss_Reader_BackEnd.Models.CategoryItem", b =>
                {
                    b.HasOne("Rss_Reader_BackEnd.Models.Item", "Item")
                        .WithMany("CategoryItems")
                        .HasForeignKey("ItemForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Rss_Reader_BackEnd.Models.Item", b =>
                {
                    b.Navigation("CategoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
